config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:q]
      @flats = Flat.where("name LIKE ?", "%" + params[:q] + "%")
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :picture_url, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container mt-3">

<div class="row justify-content-center">
  <div class="col-6 bg-light rounded">

    <h1><%= @flat.new_record? ? 'Add a new Flat' : 'Edit flat' %></h1>
    <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :picture_url %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit @flat.new_record? ? 'Create Flat' : 'Edit flat', class: 'btn btn-primary mt-3' %>
    <%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-danger mt-3' %>

    <% end %>

  </div>
</div>

</div>

app/views/flats/edit.html.erb
<%= render partial: 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container mt-3">

<div class="row">
    <div class="col-12">
      <h1>All our Flats (<%= @flats.count %>)</h1>
    </div>
  </div>

<div class="row">
<% @flats.each do |flat| %>
  <div class="col-4">
    <div class="card mb-3">
      <%= image_tag(flat.picture_url, height: '240', class: 'card-img-top') %>
      <div class="card-body card-header">
        <h5 class="card-title"><%= flat.name %></h5>
        <p class="card-text"><%= flat.address %></p>
        <div class="d-flex">
          <div class="">
            <%= icon('fas', 'user-friends', class: 'mr-3') %>
            <span> <%= flat.number_of_guests %></span>
          </div>
          <div class="px-3">
            <%= icon('fas', 'dollar-sign', class: 'mr-3') %>
            <span> <%= flat.price_per_night %> </span>
          </div>
        </div>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
        <%= link_to 'More info', flat_path(flat), class: 'link-primary' %>
        <%= link_to 'Edit', edit_flat_path(flat), class: 'ms-3 link-warning' %>
        <%= link_to 'Remove', flat_path(flat), class: 'ms-3 link-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
        </li>
      </ul>
    </div>
  </div>
<% end %>
</div>

</div>

app/views/flats/new.html.erb
<div class="row justify-content-center">
  <div class="col-6 bg-light rounded">

    <h1>Add a new Flat</h1>
    <%= simple_form_for @flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :picture_url %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.submit "Create Flat", class: 'btn btn-primary mt-3' %>
    <%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-danger mt-3' %>

    <% end %>

  </div>
</div>

app/views/flats/show.html.erb
<div class="jumbotron jumbotron-fluid">
<%= image_tag(@flat.picture_url, height: '360', width:'100%', class: 'fit-cover') %>
</div>

<div class="container margin-top-negative">

<div class="row">

<div class="col-8">

<div class="card mb-3">
  <div class="card-body card-header">
    <h1><%= @flat.name %></h1>
    <p><%= @flat.address %></p>
  </div>
</div>

<div class="card mb-3">
<div class="card-body card-header">
    <h3>A bit more about this flat...</h3>
    <p><%= @flat.description %></p>
  </div>
</div>

<div class="card mb-5">
<div class="card-body card-header">
    <h3>Details</h3>
    <div class="d-flex">
      <div class="">
        <%= icon('fas', 'user-friends', class: 'mr-3') %>
        <span> <%= @flat.number_of_guests %></span>
      </div>
      <div class="px-3">
        <%= icon('fas', 'dollar-sign', class: 'mr-3') %>
        <span> <%= @flat.price_per_night %> </span>
      </div>
    </div>
  </div>
</div>

</div>


<div class="col-4">

<div class="card mb-3">
  <div class="card-body card-header">
    <h5>Book this place!</h5>
    <form>
      <div class="form-group">
        <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">From:</div>
        </div>
        <input type="text" class="form-control" id="from_date" placeholder="12/10/2017">
        </div>
      </div>
      <div class="form-group">
        <div class="input-group mb-2">
        <div class="input-group-prepend">
          <div class="input-group-text">To:</div>
        </div>
        <input type="text" class="form-control" id="to_date" placeholder="18/10/2017">
      </div>
      </div>
      <button type="submit" class="btn btn-success col-12">Book</button>
    </form>
  </div>
</div>

<div class="card mb-3">
  <div class="card-body card-header d-flex justify-content-between align-items-center">
    <span>Share</span>
    <div>
    <%= icon('fab', 'facebook-square', class: 'fa-2x') %>
    <%= icon('fab', 'twitter-square', class: 'fa-2x') %>
    <%= icon('fab', 'pinterest-square', class: 'fa-2x') %>
    <%= icon('fas', 'envelope-square', class: 'fa-2x') %>
    </div>
  </div>
</div>


</div>





</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Simple Airbnb', flats_path, class: 'navbar-brand' %>
        <div class="d-flex">
        <form class="d-flex mx-2" action="<%= flats_path %>">
          <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <%= link_to 'Add Flat', new_flat_path, class: 'btn btn-outline-primary' %>
        </div>
      </div>
    </nav>

    <%= yield %>
    </body>
</html>